spring:
  application:
    name: RedissonLettuce
  redis:
  data:
    redis:
      cluster:
        nodes: 192.168.80.129:6379,127.0.0.1:6379
        max-redirects: 5
        enabled: true
      lettuce:
        pool:
          enabled: true
          max-idle: 16
          min-idle: 8
          max-active: 8
          max-wait: 3000
      url: redis://root@127.0.0.1:6379
      host: 127.0.0.1
      port: 6379
      password: root
      database: 0
server:
  port: 8080